language: php
php:
  - 7.1
  
services:
  - docker
  
before_install:
  - docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .

before_script:
  - composer install --no-interaction
  - docker images ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}

script:
  - vendor/bin/phpunit

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
