language: php
php:
  - 7.1
  
services:
  - docker

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
