language: php
php:
  - 7.1

sudo: required

services:
  - docker
  
before_install:
  - apt-get -y install libxslt-dev
  - docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .

before_script:
  - composer install --no-interaction
  - docker images ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}

script:
  - vendor/bin/phpunit
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
